# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-30 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_auto_20191030_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='under_age',
            field=models.IntegerField(null=True),
        ),
    ]
