# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-30 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_auto_20191030_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='lennyface',
        ),
        migrations.RemoveField(
            model_name='application',
            name='under_age',
        ),
    ]
