# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-27 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_auto_20191030_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='application',
            name='participant',
            field=models.CharField(choices=[('Hacker', 'Hacker'), ('Volunteer', 'Volunteer'), ('Mentor', 'Mentor')], default='Hacker', max_length=300),
        ),
    ]
