# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-27 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_auto_20191127_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='mentor_topic',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='mentor_workshop',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='volunteer_time',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
