# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-29 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_auto_20191127_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='classstatus',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate Student', 'Graduate Student')], default='Freshman', max_length=300),
        ),
        migrations.AddField(
            model_name='application',
            name='first_ugahacks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='hearabout',
            field=models.CharField(choices=[('Search Engine', 'Search Engine'), ('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('GitHub', 'Github'), ('Promotional Emails', 'Promotional Emails'), ('Friends', 'Friends'), ('Professors/University-wide annoucement', 'Professors/University-wide annoucement'), ('Enjoyed the last one/Want to attend again', 'Enjoyed the last one/Want to attend again')], default='Search Engine', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('NA', 'Prefer not to answer'), ('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary')], default='NA', max_length=23),
        ),
        migrations.AlterField(
            model_name='application',
            name='graduation_year',
            field=models.IntegerField(choices=[(2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], default=2019),
        ),
        migrations.AlterField(
            model_name='application',
            name='tshirt_size',
            field=models.CharField(choices=[('XXS', 'Unisex - XXS'), ('XS', 'Unisex - XS'), ('S', 'Unisex - S'), ('M', 'Unisex - M'), ('L', 'Unisex - L'), ('XL', 'Unisex - XL'), ('XXL', 'Unisex - XXL')], default='M', max_length=5),
        ),
    ]
