# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-30 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0026_auto_20191129_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='classstatus',
            new_name='class_status',
        ),
    ]
