# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-12-15 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_auto_20191130_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='code_of_conduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='uniemail',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='university_email'),
        ),
        migrations.AlterField(
            model_name='application',
            name='hearabout',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Search Engine', 'Search Engine'), ('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('GitHub', 'Github'), ('Promotional Emails', 'Promotional Emails'), ('Friends', 'Friends'), ('Professors/University-wide annoucement', 'Professors/University-wide annoucement'), ('Enjoyed the last one/Want to attend again', 'Enjoyed the last one/Want to attend again')], default='N/A', max_length=50),
        ),
    ]
