# Generated by Django 2.2.10 on 2020-04-19 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0028_auto_20200110_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(default=1234567890, max_length=14, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the following format:                                                                 (999) 999-9999', regex='^\\(\\d{3}\\)\\s\\d{3}-\\d{4}')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='class_status',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate Student', 'Graduate Student'), ('Graduated', 'Graduated')], default='Freshman', max_length=300),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_timer',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_ugahacks',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='hearabout',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Search Engine', 'Search Engine'), ('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('GitHub', 'Github'), ('Promotional Emails', 'Promotional Emails'), ('Friends', 'Friends'), ('Professors/University-wide annoucement', 'Professors/University-wide annoucement'), ('MLH Website', 'MLH Website')], default='N/A', max_length=50),
        ),
    ]
