# Generated by Django 2.2.10 on 2020-05-31 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0029_auto_20200328_1720'),
        ('applications', '0029_auto_20200419_1858'),
    ]

    operations = [
    ]
