# Generated by Django 2.2.13 on 2020-07-22 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0029_auto_20200718_1956'),
        ('applications', '0029_auto_20200722_1519'),
    ]

    operations = [
    ]
