# Generated by Django 2.2.13 on 2020-10-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0030_merge_20200722_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hacks_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
