# Generated by Django 2.2.13 on 2020-10-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0031_application_hacks_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
