# Generated by Django 2.2.13 on 2020-06-28 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0030_auto_20200601_1804'),
        ('applications', '0031_auto_20200531_0117'),
    ]

    operations = [
    ]
