# Generated by Django 2.2.13 on 2020-10-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0033_auto_20201018_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='address',
            new_name='address_line',
        ),
        migrations.AddField(
            model_name='application',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
