# Generated by Django 2.2.13 on 2020-10-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0034_auto_20201018_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='attendance_type',
            field=models.CharField(choices=[('DIGITAL', 'Digital'), ('In-person', 'In-person')], default='In-person', max_length=300),
        ),
    ]
