# Generated by Django 2.2.13 on 2020-10-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0035_application_attendance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='attendance_type',
            field=models.CharField(choices=[('Virtual', 'Virtual'), ('In-person', 'In-person')], default='In-person', max_length=300),
        ),
    ]
