# Generated by Django 2.2.13 on 2020-10-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0036_auto_20201018_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='diet',
            field=models.CharField(choices=[('None', 'None'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Halal', 'Halal'), ('Kosher', 'Kosher'), ('Gluten-free', 'Gluten-free'), ('No pork', 'No pork'), ('No peanuts/nuts', 'No peanuts/nuts'), ('No dairy', 'No dairy'), ('Others', 'Others')], default='None', max_length=300),
        ),
    ]
