# Generated by Django 2.2.13 on 2020-12-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0037_auto_20201019_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='attendance_type',
            field=models.CharField(choices=[('Virtual', 'Virtual'), ('In-person', 'In-person')], default='Virtual', max_length=300),
        ),
        migrations.AlterField(
            model_name='application',
            name='hearabout',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Search Engine', 'Search Engine'), ('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('GitHub', 'Github'), ('Promotional Emails', 'Promotional Emails'), ('Friends', 'Friends'), ('Professors/University-wide announcement', 'Professors/University-wide announcement'), ('MLH Website', 'MLH Website')], default='N/A', max_length=50),
        ),
    ]
