# Generated by Django 2.2.13 on 2021-01-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0038_auto_20201219_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='MLH_promotional',
            field=models.BooleanField(default=False),
        ),
    ]
