# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-12-15 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('description', models.CharField(max_length=300, null=True)),
                ('location', models.CharField(max_length=63)),
                ('host', models.CharField(max_length=63)),
                ('open', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='timeslot',
            name='workshop',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshops.Workshop'),
        ),
    ]
