# Generated by Django 2.2.13 on 2020-12-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='in_person',
            field=models.BooleanField(default=True),
        ),
    ]
