# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-06 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_auto_20191215_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='workshop',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='workshop_one',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_one_set', to='workshops.Workshop'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='workshop_two',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_two_set', to='workshops.Workshop'),
        ),
    ]
