# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-11 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_auto_20200110_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='location',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
