# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-16 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0008_auto_20200115_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='end',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='start',
        ),
    ]
