# Generated by Django 2.2.10 on 2020-03-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0009_auto_20200115_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
