# Generated by Django 2.2.10 on 2020-03-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='tier',
            field=models.CharField(choices=[('Tier 1', 'Doghouse'), ('Tier 2', 'Apartment'), ('Tier 3', 'Penthouse'), ('Co-Host', 'Mansion')], max_length=255),
        ),
    ]
