# Generated by Django 2.2.10 on 2020-04-17 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_auto_20200416_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorapplication',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='sponsorapplication',
            name='password',
        ),
    ]
