# Generated by Django 2.2.10 on 2020-05-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_auto_20200416_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='tier',
            field=models.CharField(choices=[('Tier1', 'Doghouse'), ('Tier2', 'Apartment'), ('Tier3', 'Penthouse'), ('Co-Host', 'Mansion')], max_length=255),
        ),
    ]
