# Generated by Django 2.2.10 on 2020-05-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('checkin', '0002_checkin_qr_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
