# Generated by Django 2.2.10 on 2020-05-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_checkin_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
