# Generated by Django 2.2 on 2020-03-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_is_hx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_hx',
        ),
        migrations.AddField(
            model_name='user',
            name='is_sponsor',
            field=models.BooleanField(default=False),
        ),
    ]
