# Generated by Django 2.2.10 on 2020-04-19 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_is_hx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_hx',
        ),
    ]
