# Generated by Django 2.2.10 on 2020-05-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_is_hx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='on_duty',
            field=models.BooleanField(default=False),
        ),
    ]
