# Generated by Django 2.2.13 on 2020-07-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default_profile_picture.jpg', upload_to='profile_pictures'),
        ),
    ]
