# Generated by Django 2.2.10 on 2020-06-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200525_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_hx',
        ),
    ]
