# Generated by Django 2.2.10 on 2020-06-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200525_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='on_duty_time',
            field=models.DateTimeField(null=True),
        ),
    ]
