# Generated by Django 2.2.10 on 2020-06-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_on_duty_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='on_duty_time',
        ),
        migrations.AddField(
            model_name='user',
            name='duty_update_time',
            field=models.DateTimeField(null=True, verbose_name='Last Checked In'),
        ),
    ]
